spring:
  profiles:
    active: dev


  #全局 若是值是null，就不会返回
  #  jackson:
  #    default-property-inclusion: non_null

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    port: 5672

server:
  port: 8040
  servlet:
    context-path: /nettyChat


tcp:
  port: 8485
  # worker的线程数
  worker:
    thread:
      count: 2

  #是否使用长连接
  so:
    keepalive:  true
    backlog: 100

