spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/nettyChat?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: vily
    password: Jhaku114@

  jpa:
    hibernate:
    ddl-auto: creat
    show-sql: true